#!/usr/bin/bash
PROTO=${1:-5state_MFCC_E_D_A}
# Path of List of training data
LISTINIT=../list/list_init_train.scp


../scripts/multi_Initialise_models $LISTINIT $PROTO
../scripts/multi_train_models $LISTINIT
