#!/usr/bin/bash

# to use your own data, this automatically sets USER to be your username
# USER=${USER:-`whoami`}

USER=${1:-`whoami`}
# and this is the path to where your data was placed by the make_mfccs script
DATA=${2:-../data_local}

# later, to use another user's data, for example "simonk"
# USER=simonk
# and to access all data from all years, use this path
echo $USER


# how many states is determined by the choice of prototype model
# remember - two of these states are dummy, so the 3state model only
# has a single emitting state

PROTO=5state
set -x

# initialise each model
for WORD in `cat ../resources/seq_word_list`
do

 echo Initialising model of $WORD

 HInit -T 1 \
	-G ESPS \
        -m 1 \
        -C ../resources/CONFIG \
        -l $WORD \
        -M ../models/hmm0 \
        -o $WORD \
        -L ${DATA}/lab/train \
	../models/proto/$PROTO \
	${DATA}/mfcc/train/${USER}_train.mfcc

  HRest -T 1 \
   -G ESPS \
         -m 1 \
         -C ../resources/CONFIG \
         -l $WORD \
         -M ../models/hmm1 \
         -L ${DATA}/lab/train/ \
   ../models/hmm0/$WORD \
   ${DATA}/mfcc/train/${USER}_train.mfcc

done
